image: docker:stable

services:
  - docker:dind

variables:
  CONTAINER_IMAGE: docker.janguo.de/comba
  DOCKER_DRIVER: overlay
  GIT_SUBMODULE_STRATEGY: normal

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.janguo.de

build:
  stage: build
  only:
    - tags
  script:
    - docker pull $CONTAINER_IMAGE:latest
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
    - docker push $CONTAINER_IMAGE:latest